### ISSUE TITLE
Unreachable code after return statement

### ISSUE THREAD

**Issue by rezoner** [mozilla/devtools-perf-game#24]

**Comment by aesedepece** [comment]
As read in MDN:

> **Automatic Semicolon Insertion**
> The return statement is affected by automatic semicolon insertion (ASI). No line terminator is allowed between the return keyword and the expression.
> 
> ``` javascript
> return
> a + b;
> ```
> 
> is transformed by ASI into:
> 
> ``` javascript
> return; 
> a + b;
> ```
> 
> Starting with Gecko 40 the console will warn "unreachable code after return statement".

Link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return
