### ISSUE TITLE
Power Surge game doesn't load if you have HTTPS Everywhere addon installed (due to its codepen rule)

### ISSUE THREAD

**Issue by dholbert** [mozilla/devtools-perf-game#27]
STR:
 1. Install HTTPS Everywhere from https://www.eff.org/https-everywhere
 2. Restart Firefox to complete installation.
 3. Visit Power Surge game: http://codepen.io/mozhacks/pen/xGgevw

OR, alternately, just directly load the HTTPS version of the game:
 https://codepen.io/mozhacks/pen/xGgevw

ACTUAL RESULTS:
Game doesn't load in the lower CodePen window. (All that shows up is a Firefox Dev edition icon with a chat bubble.) Moreover, there's a shield in URL bar indicating that insecure content was blocked.

If you edit the CodePen source to use "//" URIs instead of "http://" URIs, then we'll load the correct HTTPS versions of resources. Here's a forked version with that fixed:
  https://codepen.io/anon/pen/BNWzMj

(I still see some logged lines in the console about blocked resources, which seem to be from HTTP URIs that are hardcoded in our github-hosted scripts -- e.g. "gameover.ogg". We need to fix that as well, but that's probably less high-priority.)

**Comment by canuckistani** [comment]
Awesome - thanks for reporting this!

**Comment by digitarald** [comment]
Fixed the codepen, only sound seems to be missing now. Commit incoming.
